export const egyptGovernorates = [
    { "name": "القاهرة", "url": "cairo" },
    { "name": "الإسماعيلية", "url": "ismailia" },
    { "name": "الجيزة", "url": "giza" },
    { "name": "الأسكندرية", "url": "alexandria" },
    { "name": "الدقهلية", "url": "dakahlia" },
    { "name": "البحيرة", "url": "beheira" },
    { "name": "الفيوم", "url": "fayoum" },
    { "name": "الغربية", "url": "gharbia" },
    { "name": "المنوفية", "url": "monufia" },
    { "name": "المنيا", "url": "minya" },
    { "name": "القليوبية", "url": "qalyubia" },
    { "name": "السويس", "url": "suez" },
    { "name": "أسوان", "url": "aswan" },
    { "name": "أسيوط", "url": "asyut" },
    { "name": "بورسعيد", "url": "port-said" },
    { "name": "دمياط", "url": "damietta" },
    { "name": "الشرقية", "url": "sharqia" },
    { "name": "مطروح", "url": "matrouh" },
    { "name": "الأقصر", "url": "luxor" },
    { "name": "قنا", "url": "qena" },
    { "name": "العريش", "url": "العريش" },
    { "name": "الغردقة", "url": "الغردقة" },
    { "name": "سوهاج", "url": "sohag" }
];